default_context:
  project_name: 'fast_api_test'
  project_slug: 'fast_api_test'
  domain_main: 'fast_api_test.com'
  domain_staging: 'stag.fast_api_test.com'
  docker_swarm_stack_name_main: 'fast_api_test-com'
  docker_swarm_stack_name_staging: 'stag-fast_api_test-com'
  secret_key: '4c968d0ed8e33743576914799fafeeb479b51aa28d7aa7e04c70e6c855c01e56'
  first_superuser: 'admin@fast_api_test.com'
  first_superuser_password: 'MTAk93cz@mtb;^f(eq#LV?'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fast_api_test.com", "https://stag.fast_api_test.com", "https://fast_api_test.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fast_api_test.com'
  postgres_password: 'jnY<a,UAmC7Q;~!94u@H}J'
  pgadmin_default_user: 'admin@fast_api_test.com'
  pgadmin_default_user_password: 'MTAk93cz@mtb;^f(eq#LV?'
  traefik_constraint_tag: 'fast_api_test.com'
  traefik_constraint_tag_staging: 'stag.fast_api_test.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:MTAk93cz@mtb;^f(eq#LV?'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
